// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: polarx_expect.proto

#include "polarx_expect.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace PolarXRPC {
namespace Expect {
constexpr Open_Condition::Open_Condition(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : condition_value_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , condition_key_(0u)
  , op_(0)
{}
struct Open_ConditionDefaultTypeInternal {
  constexpr Open_ConditionDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Open_ConditionDefaultTypeInternal() {}
  union {
    Open_Condition _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Open_ConditionDefaultTypeInternal _Open_Condition_default_instance_;
constexpr Open::Open(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : cond_()
  , op_(0)
{}
struct OpenDefaultTypeInternal {
  constexpr OpenDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~OpenDefaultTypeInternal() {}
  union {
    Open _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT OpenDefaultTypeInternal _Open_default_instance_;
constexpr Close::Close(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct CloseDefaultTypeInternal {
  constexpr CloseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CloseDefaultTypeInternal() {}
  union {
    Close _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CloseDefaultTypeInternal _Close_default_instance_;
}  // namespace Expect
}  // namespace PolarXRPC
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_polarx_5fexpect_2eproto[3];
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_polarx_5fexpect_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_polarx_5fexpect_2eproto = nullptr;

const uint32_t TableStruct_polarx_5fexpect_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open_Condition, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open_Condition, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open_Condition, condition_key_),
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open_Condition, condition_value_),
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open_Condition, op_),
  1,
  0,
  2,
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open, op_),
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Open, cond_),
  0,
  ~0u,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::PolarXRPC::Expect::Close, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::PolarXRPC::Expect::Open_Condition)},
  { 12, 20, -1, sizeof(::PolarXRPC::Expect::Open)},
  { 22, -1, -1, sizeof(::PolarXRPC::Expect::Close)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PolarXRPC::Expect::_Open_Condition_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PolarXRPC::Expect::_Open_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::PolarXRPC::Expect::_Close_default_instance_),
};

const char descriptor_table_protodef_polarx_5fexpect_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023polarx_expect.proto\022\020PolarXRPC.Expect\""
  "\211\003\n\004Open\022E\n\002op\030\001 \001(\0162#.PolarXRPC.Expect."
  "Open.CtxOperation:\024EXPECT_CTX_COPY_PREV\022"
  ".\n\004cond\030\002 \003(\0132 .PolarXRPC.Expect.Open.Co"
  "ndition\032\311\001\n\tCondition\022\025\n\rcondition_key\030\001"
  " \002(\r\022\027\n\017condition_value\030\002 \001(\014\022N\n\002op\030\003 \001("
  "\01623.PolarXRPC.Expect.Open.Condition.Cond"
  "itionOperation:\rEXPECT_OP_SET\"<\n\022Conditi"
  "onOperation\022\021\n\rEXPECT_OP_SET\020\000\022\023\n\017EXPECT"
  "_OP_UNSET\020\001\">\n\014CtxOperation\022\030\n\024EXPECT_CT"
  "X_COPY_PREV\020\000\022\024\n\020EXPECT_CTX_EMPTY\020\001\"\007\n\005C"
  "loseB\036\n\034com.mysql.cj.polarx.protobuf"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_polarx_5fexpect_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_polarx_5fexpect_2eproto = {
  false, false, 476, descriptor_table_protodef_polarx_5fexpect_2eproto, "polarx_expect.proto", 
  &descriptor_table_polarx_5fexpect_2eproto_once, nullptr, 0, 3,
  schemas, file_default_instances, TableStruct_polarx_5fexpect_2eproto::offsets,
  file_level_metadata_polarx_5fexpect_2eproto, file_level_enum_descriptors_polarx_5fexpect_2eproto, file_level_service_descriptors_polarx_5fexpect_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_polarx_5fexpect_2eproto_getter() {
  return &descriptor_table_polarx_5fexpect_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_polarx_5fexpect_2eproto(&descriptor_table_polarx_5fexpect_2eproto);
namespace PolarXRPC {
namespace Expect {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Open_Condition_ConditionOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_polarx_5fexpect_2eproto);
  return file_level_enum_descriptors_polarx_5fexpect_2eproto[0];
}
bool Open_Condition_ConditionOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Open_Condition_ConditionOperation Open_Condition::EXPECT_OP_SET;
constexpr Open_Condition_ConditionOperation Open_Condition::EXPECT_OP_UNSET;
constexpr Open_Condition_ConditionOperation Open_Condition::ConditionOperation_MIN;
constexpr Open_Condition_ConditionOperation Open_Condition::ConditionOperation_MAX;
constexpr int Open_Condition::ConditionOperation_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Open_CtxOperation_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_polarx_5fexpect_2eproto);
  return file_level_enum_descriptors_polarx_5fexpect_2eproto[1];
}
bool Open_CtxOperation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr Open_CtxOperation Open::EXPECT_CTX_COPY_PREV;
constexpr Open_CtxOperation Open::EXPECT_CTX_EMPTY;
constexpr Open_CtxOperation Open::CtxOperation_MIN;
constexpr Open_CtxOperation Open::CtxOperation_MAX;
constexpr int Open::CtxOperation_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class Open_Condition::_Internal {
 public:
  using HasBits = decltype(std::declval<Open_Condition>()._has_bits_);
  static void set_has_condition_key(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_condition_value(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_op(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000002) ^ 0x00000002) != 0;
  }
};

Open_Condition::Open_Condition(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:PolarXRPC.Expect.Open.Condition)
}
Open_Condition::Open_Condition(const Open_Condition& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  condition_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    condition_value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (from._internal_has_condition_value()) {
    condition_value_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_condition_value(), 
      GetArenaForAllocation());
  }
  ::memcpy(&condition_key_, &from.condition_key_,
    static_cast<size_t>(reinterpret_cast<char*>(&op_) -
    reinterpret_cast<char*>(&condition_key_)) + sizeof(op_));
  // @@protoc_insertion_point(copy_constructor:PolarXRPC.Expect.Open.Condition)
}

inline void Open_Condition::SharedCtor() {
condition_value_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  condition_value_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&condition_key_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&op_) -
    reinterpret_cast<char*>(&condition_key_)) + sizeof(op_));
}

Open_Condition::~Open_Condition() {
  // @@protoc_insertion_point(destructor:PolarXRPC.Expect.Open.Condition)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Open_Condition::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  condition_value_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void Open_Condition::ArenaDtor(void* object) {
  Open_Condition* _this = reinterpret_cast< Open_Condition* >(object);
  (void)_this;
}
void Open_Condition::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Open_Condition::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Open_Condition::Clear() {
// @@protoc_insertion_point(message_clear_start:PolarXRPC.Expect.Open.Condition)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    condition_value_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&condition_key_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&op_) -
        reinterpret_cast<char*>(&condition_key_)) + sizeof(op_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Open_Condition::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required uint32 condition_key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_condition_key(&has_bits);
          condition_key_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional bytes condition_value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_condition_value();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional .PolarXRPC.Expect.Open.Condition.ConditionOperation op = 3 [default = EXPECT_OP_SET];
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::PolarXRPC::Expect::Open_Condition_ConditionOperation_IsValid(val))) {
            _internal_set_op(static_cast<::PolarXRPC::Expect::Open_Condition_ConditionOperation>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(3, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Open_Condition::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PolarXRPC.Expect.Open.Condition)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required uint32 condition_key = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_condition_key(), target);
  }

  // optional bytes condition_value = 2;
  if (cached_has_bits & 0x00000001u) {
    target = stream->WriteBytesMaybeAliased(
        2, this->_internal_condition_value(), target);
  }

  // optional .PolarXRPC.Expect.Open.Condition.ConditionOperation op = 3 [default = EXPECT_OP_SET];
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      3, this->_internal_op(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PolarXRPC.Expect.Open.Condition)
  return target;
}

size_t Open_Condition::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PolarXRPC.Expect.Open.Condition)
  size_t total_size = 0;

  // required uint32 condition_key = 1;
  if (_internal_has_condition_key()) {
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32SizePlusOne(this->_internal_condition_key());
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // optional bytes condition_value = 2;
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_condition_value());
  }

  // optional .PolarXRPC.Expect.Open.Condition.ConditionOperation op = 3 [default = EXPECT_OP_SET];
  if (cached_has_bits & 0x00000004u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_op());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Open_Condition::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Open_Condition::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Open_Condition::GetClassData() const { return &_class_data_; }

void Open_Condition::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Open_Condition *>(to)->MergeFrom(
      static_cast<const Open_Condition &>(from));
}


void Open_Condition::MergeFrom(const Open_Condition& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PolarXRPC.Expect.Open.Condition)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _internal_set_condition_value(from._internal_condition_value());
    }
    if (cached_has_bits & 0x00000002u) {
      condition_key_ = from.condition_key_;
    }
    if (cached_has_bits & 0x00000004u) {
      op_ = from.op_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Open_Condition::CopyFrom(const Open_Condition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PolarXRPC.Expect.Open.Condition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Open_Condition::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void Open_Condition::InternalSwap(Open_Condition* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &condition_value_, lhs_arena,
      &other->condition_value_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Open_Condition, op_)
      + sizeof(Open_Condition::op_)
      - PROTOBUF_FIELD_OFFSET(Open_Condition, condition_key_)>(
          reinterpret_cast<char*>(&condition_key_),
          reinterpret_cast<char*>(&other->condition_key_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Open_Condition::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_polarx_5fexpect_2eproto_getter, &descriptor_table_polarx_5fexpect_2eproto_once,
      file_level_metadata_polarx_5fexpect_2eproto[0]);
}

// ===================================================================

class Open::_Internal {
 public:
  using HasBits = decltype(std::declval<Open>()._has_bits_);
  static void set_has_op(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Open::Open(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  cond_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:PolarXRPC.Expect.Open)
}
Open::Open(const Open& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_),
      cond_(from.cond_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  op_ = from.op_;
  // @@protoc_insertion_point(copy_constructor:PolarXRPC.Expect.Open)
}

inline void Open::SharedCtor() {
op_ = 0;
}

Open::~Open() {
  // @@protoc_insertion_point(destructor:PolarXRPC.Expect.Open)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Open::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Open::ArenaDtor(void* object) {
  Open* _this = reinterpret_cast< Open* >(object);
  (void)_this;
}
void Open::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Open::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Open::Clear() {
// @@protoc_insertion_point(message_clear_start:PolarXRPC.Expect.Open)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cond_.Clear();
  op_ = 0;
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Open::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // optional .PolarXRPC.Expect.Open.CtxOperation op = 1 [default = EXPECT_CTX_COPY_PREV];
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          uint64_t val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          if (PROTOBUF_PREDICT_TRUE(::PolarXRPC::Expect::Open_CtxOperation_IsValid(val))) {
            _internal_set_op(static_cast<::PolarXRPC::Expect::Open_CtxOperation>(val));
          } else {
            ::PROTOBUF_NAMESPACE_ID::internal::WriteVarint(1, val, mutable_unknown_fields());
          }
        } else
          goto handle_unusual;
        continue;
      // repeated .PolarXRPC.Expect.Open.Condition cond = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_cond(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Open::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PolarXRPC.Expect.Open)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .PolarXRPC.Expect.Open.CtxOperation op = 1 [default = EXPECT_CTX_COPY_PREV];
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      1, this->_internal_op(), target);
  }

  // repeated .PolarXRPC.Expect.Open.Condition cond = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_cond_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_cond(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PolarXRPC.Expect.Open)
  return target;
}

size_t Open::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PolarXRPC.Expect.Open)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PolarXRPC.Expect.Open.Condition cond = 2;
  total_size += 1UL * this->_internal_cond_size();
  for (const auto& msg : this->cond_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // optional .PolarXRPC.Expect.Open.CtxOperation op = 1 [default = EXPECT_CTX_COPY_PREV];
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_op());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Open::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Open::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Open::GetClassData() const { return &_class_data_; }

void Open::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Open *>(to)->MergeFrom(
      static_cast<const Open &>(from));
}


void Open::MergeFrom(const Open& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PolarXRPC.Expect.Open)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cond_.MergeFrom(from.cond_);
  if (from._internal_has_op()) {
    _internal_set_op(from._internal_op());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Open::CopyFrom(const Open& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PolarXRPC.Expect.Open)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Open::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(cond_))
    return false;
  return true;
}

void Open::InternalSwap(Open* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  cond_.InternalSwap(&other->cond_);
  swap(op_, other->op_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Open::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_polarx_5fexpect_2eproto_getter, &descriptor_table_polarx_5fexpect_2eproto_once,
      file_level_metadata_polarx_5fexpect_2eproto[1]);
}

// ===================================================================

class Close::_Internal {
 public:
};

Close::Close(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase(arena, is_message_owned) {
  // @@protoc_insertion_point(arena_constructor:PolarXRPC.Expect.Close)
}
Close::Close(const Close& from)
  : ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PolarXRPC.Expect.Close)
}





const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Close::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::CopyImpl,
    ::PROTOBUF_NAMESPACE_ID::internal::ZeroFieldsBase::MergeImpl,
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Close::GetClassData() const { return &_class_data_; }







::PROTOBUF_NAMESPACE_ID::Metadata Close::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_polarx_5fexpect_2eproto_getter, &descriptor_table_polarx_5fexpect_2eproto_once,
      file_level_metadata_polarx_5fexpect_2eproto[2]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Expect
}  // namespace PolarXRPC
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PolarXRPC::Expect::Open_Condition* Arena::CreateMaybeMessage< ::PolarXRPC::Expect::Open_Condition >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PolarXRPC::Expect::Open_Condition >(arena);
}
template<> PROTOBUF_NOINLINE ::PolarXRPC::Expect::Open* Arena::CreateMaybeMessage< ::PolarXRPC::Expect::Open >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PolarXRPC::Expect::Open >(arena);
}
template<> PROTOBUF_NOINLINE ::PolarXRPC::Expect::Close* Arena::CreateMaybeMessage< ::PolarXRPC::Expect::Close >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PolarXRPC::Expect::Close >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
